import { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';

export type AppLanguage = 'en' | 'am' | 'or' | 'ar';

type TranslationKey = keyof typeof translations.en;

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: TranslationKey) => string;
  dir: 'ltr' | 'rtl';
};

const translations = {
  en: {
    studentPanelButton: 'Student Panel',
    adminPanelButton: 'Admin Panel',
    studentPanelHeroTitle: 'BILALUL HABESHI PHOTOGRAPHY & VIDEOGRAPHY TRAINING CENTER',
    studentPanelHeroSubtitle: 'STUDENT PORTAL VIEW YOUR LATEST RESULT',
    studentSearchTitle: 'Search Your Result',
    enterStudentIdPlaceholder: 'Enter your Student ID',
    adminPanelHeroTitle: 'Admin Panel',
    languageButton: 'Language',
    englishLabel: 'English',
    amharicLabel: 'Amharic',
    oromoLabel: 'Afaan Oromoo',
    arabicLabel: 'Arabic',
    schoolNewsHeading: 'School News & Announcements',
    schoolNewsTitle: 'School News',
    noAnnouncements: 'No announcements at this time',
    clearAll: 'Clear All',
    noNewNotifications: 'No new notifications',
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    addGradesTitle: 'Add Grades',
    editAllGradesTitle: 'Edit All Grades',
    uploadPhoto: 'Upload Photo',
    studentIdPlaceholder: 'Student ID (e.g., S1001)',
    studentNamePlaceholder: 'Student Name',
    batchNumberPlaceholder: 'e.g., Batch 10',
    subjectNameLabel: 'Subject Name',
    genderLabel: 'Gender',
    genderPlaceholder: 'Select gender',
    genderMale: 'Male',
    genderFemale: 'Female',
    genderAllOption: 'All Gender',
    subjectsAndGrades: 'Subjects & Grades',
    cancel: 'Cancel',
    addLabel: 'Add',
    addSubject: 'Add Subject',
    updateLabel: 'Update',
    gradeLabel: 'Grade',
    outOfLabel: 'Out of',
    saveGrades: 'Save Grades',
    updateGrades: 'UPDATE',
    gradeLetterColumn: 'GRADE LETTER',
    gradeLetterOnAll: 'ON ALL',
    gradeLetterOffAll: 'OFF ALL',
    viewColumn: 'VIEW & RE-EDIT',
    lockColumn: 'LOCK',
    deleteColumn: 'DELETE',
    recentComments: 'Recent Student Comments',
    recentTeacherComments: 'Recent Teacher Comments',
    noRecentComments: 'No recent comments',
    noNewComments: "You don't have a new comment",
    reply: 'Reply',
    chatWithTeacher: 'Chat with Teacher',
    noMessagesYet: 'No messages yet',
    teacherLabel: 'Teacher',
    youLabel: 'You',
    messagePlaceholder: 'Ask a question or report a correction...',
    searchPlaceholder: 'Search by name or ID...',
    filterGradesLabel: 'FILTER BY GRADES',
    filterBatchLabel: 'FILTER BY STUDENT BATCH',
    filterGenderLabel: 'FILTER BY GENDER',
    allStudents: 'All Students',
    photoColumn: 'Photo',
    idColumn: 'ID',
    nameColumn: 'Name',
    batchColumn: 'Batch',
    subjectsColumn: 'Subj',
    avgGradeColumn: 'Avg Grade',
    actionsColumn: 'Actions',
    viewButton: 'View',
    gradeLetterOnLabel: 'Grade Letter ON',
    gradeLetterOffLabel: 'Grade Letter OFF',
    signOut: 'Sign Out',
    poweredBy: 'Powered By',
    languageMenuTitle: 'Change Language',
    languageHint: 'Choose how the app speaks to you',
    noGrades: 'No grades',
    newLabel: 'New',
    studentGradeReportTitle: 'Student Grade Report',
    showAllResults: 'See all results',
    hideAllResults: 'Hide results',
    totalSubjectsLabel: 'Total Subjects',
    totalGradeLabel: 'Total Grade',
    allSubjectsAndGradesTitle: 'All Subjects & Grades',
    studentToggleLabel: 'For Students Panel Only',
    managementToggleLabel: 'Management Panel',
    adminAccessTitle: 'Admin Access',
    adminAccessSubtitle: 'Enter password to continue',
    signIn: 'Sign In',
    passwordPlaceholder: 'Password',
    appLockedTitle: 'App Locked',
    appLockedMessage: 'Too many incorrect attempts. Please wait.',
    appLockedFooter: 'App will return to welcome screen automatically',
    genderRequiredMessage: 'Please select a gender',
    contactInformationHeading: 'Contact Information',
    contactAdminSectionTitle: 'School Administration & Registration',
    contactSchoolAdmin: 'Contact the school admin',
    phoneLabel: 'Phone',
    ourTeachersHeading: 'Our Teachers',
    noTeacherInfo: 'No teacher information available',
    teacherManagementTitle: 'Teacher Management',
    addTeacherButton: 'Add Teacher',
    editTeacherTitle: 'Edit Teacher',
    teacherNamePlaceholder: 'Teacher Name',
    teacherPhonePlaceholder: 'Phone Number',
    teacherSubjectPlaceholder: 'Subject',
    teacherTelegramPlaceholder: 'Telegram Username (optional)',
    newsManagementTitle: 'News Management',
    addNewsButton: 'Add News',
    editNewsTitle: 'Edit News',
    publishNotifyButton: 'Publish & Notify',
    noNewsMessage: 'No news added yet',
    contactInformationManagementTitle: 'Contact Information Management',
    addPhoneNumberButton: 'Add Phone Number',
    schoolPhoneNumbersLabel: 'School Phone Numbers',
    contactTextLabel: 'Contact Text (displayed with phone numbers)',
    contactTextPlaceholder: 'e.g., Contact School Admin & Registration',
    saveContactInformationButton: 'Save Contact Information',
    savingLabel: 'Saving...',
    currentSettingsLabel: 'Current Settings:',
    portalUnderMaintenance: 'Portal Under Maintenance',
    portalClosedMessage: 'The student portal is currently closed for updates or maintenance.',
    portalContactMessage: 'Please contact the school administration or check back later.',
    noResultsFound: 'No results found.',
    yourGrades: 'Your Grades',
    cinematography: 'Cinematography',
    videoEditing: 'Vision & Sound Editing',
    teacherNotSubmitted: 'Your teacher has not submitted your grades yet.',
    pleaseContactThem: 'Please contact them.',
    noGradesAvailable: 'No grades available yet.',
    editMessage: 'Edit Message',
    deleteMessage: 'Delete Message',
    saveChanges: 'Save Changes',
    dismiss: 'Dismiss',
    export: 'Export',
    exportGradeReport: 'Export Grade Report',
    studentIdLabel: 'Student ID',
    newMessageTitle: 'New Message',
    newMessageDescription: 'You have received a new message from your teacher.',
    viewAndReply: 'View & Reply',
    studentLabel: 'Student',
    replyPlaceholder: 'Reply to student...',
    replySent: 'Reply sent!',
    replyFailed: 'Failed to send reply',
    superAdminAccess: 'Super Admin Access',
    manageMasterPassword: 'Manage master access password',
    changePassword: 'Change Password',
    newsAdminAccess: 'News Admin Access',
    manageNewsAdminAccess: 'Manage access for news administrators',
    studentAdminAccess: 'Student Admin Access',
    manageStudentAdminAccess: 'Manage access for student administrators',
    sliderManagement: 'Slider Management',
    addImage: 'Add Image',
    studentPortalAccess: 'Student Portal Access',
    portalActiveMessage: 'Students can view their results',
    portalClosedMessageAdmin: 'Portal is closed. Students see a maintenance message.',
    active: 'Active',
    closed: 'Closed',
    portalEnabledToast: 'Student portal enabled',
    portalDisabledToast: 'Student portal disabled',
    cropImage: 'Crop Image',
    applyCrop: 'Apply Crop',
    videoManagement: 'Video Management',
    addVideo: 'Add Video',
    noVideosInCategory: 'No videos in this category',
    editVideo: 'Edit Video',
    addNewVideo: 'Add New Video',
    titleLabel: 'Title',
    videoTitlePlaceholder: 'Video Title',
    videoUrlLabel: 'Video URL',
    categoryLabel: 'Category',
    subCategoryLabel: 'Sub Category',
    selectSubCategory: 'Select Sub Category',
    orderIndexLabel: 'Order Index',
    visibleToStudentsLabel: 'Visible to Students',
    save: 'Save',
    preview: 'Preview',
    edit: 'Edit',
    delete: 'Delete',
    newsTitlePlaceholder: 'News Title',
    newsContentPlaceholder: 'News Content',
    newsImageLabel: 'News Image (Optional)',
    cropSelection: 'Crop Selection',
    processing: 'Processing...',
  },
  am: {
    studentPanelButton: 'የተማሪ ፓነል',
    adminPanelButton: 'የአስተዳዳሪ ፓነል',
    studentPanelHeroTitle: 'እንኳን ወደ ቢላልሉል ሀበሺ የስልጠና ማዕከል በደህና መጡ',
    studentPanelHeroSubtitle: 'የተማሪ ፖርታል - የቅርብ ውጤትዎን ይመልከቱ',
    studentSearchTitle: 'ውጤትዎን ፈልጉ',
    enterStudentIdPlaceholder: 'የተማሪ መለያዎን ያስገቡ',
    adminPanelHeroTitle: 'የአስተዳዳሪ ፓነል',
    languageButton: 'ቋንቋ',
    englishLabel: 'እንግሊዝኛ',
    amharicLabel: 'አማርኛ',
    oromoLabel: 'ኦሮምኛ',
    arabicLabel: 'አረብኛ',
    schoolNewsHeading: 'የትምህርት ቤት ዜናና መግለጫዎች',
    schoolNewsTitle: 'የትምህርት ቤት ዜና',
    noAnnouncements: 'በአሁኑ ጊዜ ማስታወቂያ የለም',
    clearAll: 'ሁሉንም አጥፋ',
    noNewNotifications: 'አዲስ ማሳወቂያ የለም',
    notifications: 'ማሳወቂያዎች',
    noNotifications: 'ማሳወቂያ የለም',
    addGradesTitle: 'ውጤት ጨምር',
    editAllGradesTitle: 'ሁሉንም ውጤት አርትዕ',
    uploadPhoto: 'ፎቶ አስገባ',
    studentIdPlaceholder: 'የተማሪ መለያ (ለምሳሌ፣ S1001)',
    studentNamePlaceholder: 'የተማሪ ስም',
    batchNumberPlaceholder: 'ለምሳሌ፣ ባች 10',
    subjectNameLabel: 'የትምህርት ስም',
    genderLabel: 'ጾታ',
    genderPlaceholder: 'ጾታ ይምረጡ',
    genderMale: 'ወንድ',
    genderFemale: 'ሴት',
    genderAllOption: 'ሁሉም ጾታ',
    subjectsAndGrades: 'ትምህርቶች እና ውጤቶች',
    cancel: 'ሰርዝ',
    addLabel: 'ጨምር',
    addSubject: 'ትምህርት ጨምር',
    updateLabel: 'አዘምን',
    gradeLabel: 'ውጤት',
    outOfLabel: 'ከ',
    saveGrades: 'ውጤት አስቀምጥ',
    updateGrades: 'አዘምን',
    gradeLetterColumn: 'የግሬድ ፊደል',
    gradeLetterOnAll: 'ሁሉንም ክፈት',
    gradeLetterOffAll: 'ሁሉንም ዝጋ',
    viewColumn: 'እይታ እና አርትዖት',
    lockColumn: 'ቆልፍ',
    deleteColumn: 'ሰርዝ',
    recentComments: 'የተማሪዎች አስተያየቶች',
    recentTeacherComments: 'የመምህራን አስተያየቶች',
    noRecentComments: 'የቅርብ አስተያየት የለም',
    noNewComments: 'አዲስ አስተያየት የለም',
    reply: 'መልስ',
    chatWithTeacher: 'ከመምህር ጋር ይወያዩ',
    noMessagesYet: 'ገና መልዕክት የለም',
    teacherLabel: 'መምህር',
    youLabel: 'እርስዎ',
    messagePlaceholder: 'ጥያቄ ይጠይቁ ወይም ስህተት ያሳውቁ...',
    searchPlaceholder: 'በስም ወይም በመለያ ፈልግ...',
    filterGradesLabel: 'የውጤት ማጣሪያ',
    filterBatchLabel: 'የባች ማጣሪያ',
    filterGenderLabel: 'ጾታ ይማጣሩ',
    allStudents: 'ሁሉም ተማሪዎች',
    photoColumn: 'ፎቶ',
    idColumn: 'መለያ',
    nameColumn: 'ስም',
    batchColumn: 'ባች',
    subjectsColumn: 'ትምህርቶች',
    avgGradeColumn: 'አማካይ ውጤት',
    actionsColumn: 'እርምጃዎች',
    viewButton: 'እይታ',
    gradeLetterOnLabel: 'የግሬድ ፊደል ክፈት',
    gradeLetterOffLabel: 'የግሬድ ፊደል ዝጋ',
    signOut: 'ውጣ',
    poweredBy: 'በ',
    languageMenuTitle: 'ቋንቋ ለውጥ',
    languageHint: 'መተግበሪያው የሚናገረውን ቋንቋ ይምረጡ',
    noGrades: 'ውጤት የለም',
    newLabel: 'አዲስ',
    studentGradeReportTitle: 'የተማሪ ውጤት ሪፖርት',
    showAllResults: 'ሁሉንም ውጤቶች አሳይ',
    hideAllResults: 'ሁሉንም ውጤቶች ደብቅ',
    totalSubjectsLabel: 'ጠቅላላ ትምህርቶች',
    totalGradeLabel: 'ጠቅላላ ውጤት',
    allSubjectsAndGradesTitle: 'ሁሉም ትምህርቶች እና ውጤቶች',
    studentToggleLabel: 'ለተማሪዎች ፓነል ብቻ',
    managementToggleLabel: 'የአስተዳዳሪ መቆጣጠሪያ',
    adminAccessTitle: 'የአስተዳዳሪ መዳረሻ',
    adminAccessSubtitle: 'ለመቀጠል የይለፍ ቃል ያስገቡ',
    signIn: 'ግባ',
    passwordPlaceholder: 'የይለፍ ቃል',
    appLockedTitle: 'መተግበሪያው ተቆልፏል',
    appLockedMessage: 'ብዙ ጊዜ በስህተት አስገቡ። እባክዎ ይጠብቁ።',
    appLockedFooter: 'መተግበሪያው ወደ መነሻ ገጽ በራሱ ይመለሳል',
    genderRequiredMessage: 'እባክዎ ጾታ ይምረጡ',
    contactInformationHeading: 'የእውቂያ መረጃ',
    contactAdminSectionTitle: 'የትምህርት ቤት አስተዳዳሪና መመዝገቢያ',
    contactSchoolAdmin: 'የትምህርት ቤቱን አስተዳዳሪ ያነጋግሩ',
    phoneLabel: 'ስልክ',
    ourTeachersHeading: 'መምህራን ቡድናችን',
    noTeacherInfo: 'የመምህራን መረጃ አልተጨመረም',
    teacherManagementTitle: 'የመምህራን አስተዳደር',
    addTeacherButton: 'መምህር ጨምር',
    editTeacherTitle: 'መምህር አርትዕ',
    teacherNamePlaceholder: 'የመምህር ስም',
    teacherPhonePlaceholder: 'ስልክ ቁጥር',
    teacherSubjectPlaceholder: 'ትምህርት',
    teacherTelegramPlaceholder: 'የቴሌግራም ዩዘርኔም (አማራጭ)',
    newsManagementTitle: 'የዜና አስተዳደር',
    addNewsButton: 'ዜና ጨምር',
    editNewsTitle: 'ዜና አርትዕ',
    publishNotifyButton: 'አትም እና አሳውቅ',
    noNewsMessage: 'የታቀመ ዜና የለም',
    portalUnderMaintenance: 'ፖርታል በጥገና ላይ ነው',
    portalClosedMessage: 'የተማሪ ፖርታል በአሁኑ ጊዜ ለዝማኔዎች ወይም ለጥገና ተዘግቷል።',
    portalContactMessage: 'እባክዎ የትምህርት ቤት አስተዳደርን ያነጋግሩ ወይም በኋላ ተመልሰው ይሞክሩ።',
    noResultsFound: 'ምንም ውጤት አልተገኘም።',
    yourGrades: 'የእርስዎ ውጤቶች',
    cinematography: 'ሲኒማቶግራፊ',
    videoEditing: 'ቪዲዮ ኤዲቲንግ',
    teacherNotSubmitted: 'መምህርዎ እስካሁን ውጤትዎን አላስገቡም።',
    pleaseContactThem: 'እባክዎ ያነጋግሩዋቸው።',
    noGradesAvailable: 'እስካሁን ምንም ውጤት የለም።',
    editMessage: 'መልዕክት አርትዕ',
    deleteMessage: 'መልዕክት ሰርዝ',
    saveChanges: 'ለውጦችን አስቀምጥ',
    dismiss: 'አጥፋ',
    export: 'ላክ (Export)',
    exportGradeReport: 'የውጤት ሪፖርት ላክ',
    studentIdLabel: 'የተማሪ መለያ',
    newMessageTitle: 'አዲስ መልዕክት',
    newMessageDescription: 'ከመምህርዎ አዲስ መልዕክት ደርሶዎታል።',
    viewAndReply: 'ይመልከቱ እና ይመልሱ',
    studentLabel: 'ተማሪ',
    replyPlaceholder: 'ለተማሪው መልስ ይስጡ...',
    replySent: 'መልሱ ተልኳል!',
    replyFailed: 'መልስ መላክ አልተቻለም',
    contactInformationManagementTitle: 'የእውቂያ መረጃ አስተዳደር',
    addPhoneNumberButton: 'የስልክ ቁጥር ጨምር',
    schoolPhoneNumbersLabel: 'የትምህርት ቤት ስልክ ቁጥሮች',
    contactTextLabel: 'በስልክ ቁጥሮች ጋር የሚታየው ጽሑፍ',
    contactTextPlaceholder: 'ለምሳሌ፣ የትምህርት ቤት አስተዳዳሪን እና መመዝገቢያን ያነጋግሩ',
    saveContactInformationButton: 'የእውቂያ መረጃ አስቀምጥ',
    savingLabel: 'በመቀመጥ ላይ...',
    currentSettingsLabel: 'የአሁኑ ቅንብሮች፡',
    superAdminAccess: 'ዋና አስተዳዳሪ መዳረሻ',
    manageMasterPassword: 'የዋና መዳረሻ የይለፍ ቃል ያስተዳድሩ',
    changePassword: 'የይለፍ ቃል ቀይር',
    newsAdminAccess: 'የዜና አስተዳዳሪ መዳረሻ',
    manageNewsAdminAccess: 'የዜና አስተዳዳሪዎች መዳረሻን ያስተዳድሩ',
    studentAdminAccess: 'የተማሪ አስተዳዳሪ መዳረሻ',
    manageStudentAdminAccess: 'የተማሪ አስተዳዳሪዎች መዳረሻን ያስተዳድሩ',
    sliderManagement: 'የስላይደር አስተዳደር',
    addImage: 'ምስል ጨምር',
    studentPortalAccess: 'የተማሪ ፖርታል መዳረሻ',
    portalActiveMessage: 'ተማሪዎች ውጤታቸውን ማየት ይችላሉ',
    portalClosedMessageAdmin: 'ፖርታል ተዘግቷል። ተማሪዎች የጥገና መልእክት ያያሉ።',
    active: 'ንቁ',
    closed: 'ተዘግቷል',
    portalEnabledToast: 'የተማሪ ፖርታል ተከፍቷል',
    portalDisabledToast: 'የተማሪ ፖርታል ተዘግቷል',
    cropImage: 'ምስል ይቁረጡ',
    applyCrop: 'መቁረጥን ተግብር',
    videoManagement: 'የቪዲዮ አስተዳደር',
    addVideo: 'ቪዲዮ ጨምር',
    noVideosInCategory: 'በዚህ ምድብ ውስጥ ምንም ቪዲዮ የለም',
    editVideo: 'ቪዲዮ አርትዕ',
    addNewVideo: 'አዲስ ቪዲዮ ጨምር',
    titleLabel: 'ርዕስ',
    videoTitlePlaceholder: 'የቪዲዮ ርዕስ',
    videoUrlLabel: 'የቪዲዮ አገናኝ (URL)',
    categoryLabel: 'ምድብ',
    subCategoryLabel: 'ንዑስ ምድብ',
    selectSubCategory: 'ንዑስ ምድብ ይምረጡ',
    orderIndexLabel: 'የቅደም ተከተል ቁጥር',
    visibleToStudentsLabel: 'ለተማሪዎች ይታይ',
    save: 'አስቀምጥ',
    preview: 'ቅድመ እይታ',
    edit: 'አርትዕ',
    delete: 'ሰርዝ',
    newsTitlePlaceholder: 'የዜና ርዕስ',
    newsContentPlaceholder: 'የዜና ይዘት',
    newsImageLabel: 'የዜና ምስል (አማራጭ)',
    cropSelection: 'የተመረጠውን ይቁረጡ',
    processing: 'በማስኬድ ላይ...',
  },
  or: {
    studentPanelButton: 'Gabatee Barataa',
    adminPanelButton: 'Gabatee Bulchiinsaa',
    studentPanelHeroTitle: 'GIDDUGALEESSA LEENJII SUURAA FI VIIDIYOO BILAALUL HABASHII',
    studentPanelHeroSubtitle: 'PORTAALII BARATAA - BU\'AA KEESSAN ISA DHUMA ILAALAA',
    studentSearchTitle: 'Bu\'aa Keessan Barbaadaa',
    enterStudentIdPlaceholder: 'Eenyummaa Barataa Keessan Galchaa',
    adminPanelHeroTitle: 'Gabatee Bulchiinsaa',
    languageButton: 'Afaan',
    englishLabel: 'Ingiliffa',
    amharicLabel: 'Amaariffa',
    oromoLabel: 'Afaan Oromoo',
    arabicLabel: 'Afaan Arabaa',
    schoolNewsHeading: 'Oduu Mana Barumsaa fi Beeksisa',
    schoolNewsTitle: 'Oduu Mana Barumsaa',
    noAnnouncements: 'Yeroo ammaa beeksisni hin jiru',
    clearAll: 'Hunda Haqi',
    noNewNotifications: 'Beeksisni haaraa hin jiru',
    notifications: 'Beeksisawwan',
    noNotifications: 'Beeksisni hin jiru',
    addGradesTitle: 'Qabxii Galchaa',
    editAllGradesTitle: 'Qabxii Hunda Gulaalaa',
    uploadPhoto: 'Suuraa Galchaa',
    studentIdPlaceholder: 'Eenyummaa Barataa (fkn, S1001)',
    studentNamePlaceholder: 'Maqaa Barataa',
    batchNumberPlaceholder: 'fkn, Baachii 10',
    subjectNameLabel: 'Maqaa Gosa Barnootaa',
    genderLabel: 'Saala',
    genderPlaceholder: 'Saala Filadhaa',
    genderMale: 'Dhiira',
    genderFemale: 'Dubara',
    genderAllOption: 'Saala Hunda',
    subjectsAndGrades: 'Gosa Barnootaa fi Qabxii',
    cancel: 'Haqi',
    addLabel: 'Dabalata',
    addSubject: 'Gosa Barnootaa Dabalaa',
    updateLabel: 'Haaromsi',
    gradeLabel: 'Qabxii',
    outOfLabel: 'Keessaa',
    saveGrades: 'Qabxii Galchaa',
    updateGrades: 'HAAROMSI',
    gradeLetterColumn: 'QUBEE QABXII',
    gradeLetterOnAll: 'HUNDA IRRATTI',
    gradeLetterOffAll: 'HUNDA IRRAA',
    viewColumn: 'ILAALUU & IRRA DEEBI\'UU',
    lockColumn: 'CUGUU',
    deleteColumn: 'HAQUU',
    recentComments: 'Yaada Barattootaa Dhihoo',
    recentTeacherComments: 'Yaada Barsiisotaa Dhihoo',
    noRecentComments: 'Yaadni dhihoo hin jiru',
    noNewComments: "Yaada haaraa hin qabdan",
    reply: 'Deebii',
    chatWithTeacher: 'Barsiisaa Waliin Haasa\'aa',
    noMessagesYet: 'Ammatti ergaan hin jiru',
    teacherLabel: 'Barsiisaa',
    youLabel: 'Isin',
    messagePlaceholder: 'Gaaffii gaafadhaa ykn sirreeffama gabaasaa...',
    searchPlaceholder: 'Maqaa ykn ID dhaan barbaadaa...',
    filterGradesLabel: 'QABXIIDHAAN CALALUU',
    filterBatchLabel: 'BAACHII BARATAAN CALALUU',
    filterGenderLabel: 'SAALAAN CALALUU',
    allStudents: 'Barattoota Hunda',
    photoColumn: 'Suuraa',
    idColumn: 'ID',
    nameColumn: 'Maqaa',
    batchColumn: 'Baachii',
    subjectsColumn: 'Gosa Barnootaa',
    avgGradeColumn: 'Giddugaleessa',
    actionsColumn: 'Tarkaanfii',
    viewButton: 'Ilaali',
    gradeLetterOnLabel: 'Qubee Qabxii ON',
    gradeLetterOffLabel: 'Qubee Qabxii OFF',
    signOut: 'Ba\'aa',
    poweredBy: 'Kan Qopheesse',
    languageMenuTitle: 'Afaan Jijjiiraa',
    languageHint: 'Afaan ittiin isin dubbisu filadhaa',
    noGrades: 'Qabxiin hin jiru',
    newLabel: 'Haaraa',
    studentGradeReportTitle: 'Gabaasa Qabxii Barataa',
    showAllResults: 'Bu\'aa hunda argisiisi',
    hideAllResults: 'Bu\'aa dhoksi',
    totalSubjectsLabel: 'Baay\'ina Gosa Barnootaa',
    totalGradeLabel: 'Waliigala Qabxii',
    allSubjectsAndGradesTitle: 'Gosa Barnootaa fi Qabxii Hunda',
    studentToggleLabel: 'Paaneelii Barattootaa Qofaaf',
    managementToggleLabel: 'Paaneelii Bulchiinsaa',
    adminAccessTitle: 'Seensa Bulchiinsaa',
    adminAccessSubtitle: 'Itti fufuuf jechadaraa galchaa',
    signIn: 'Seenaa',
    passwordPlaceholder: 'Jechadaraa',
    appLockedTitle: 'Appilikeeshiniin Cufameera',
    appLockedMessage: 'Yaaliin dogoggoraa baay\'ateera. Maaloo eegaa.',
    appLockedFooter: 'Appilikeeshiniin ofumaan gara jalqabaatti deebi\'a',
    genderRequiredMessage: 'Maaloo saala filadhaa',
    contactInformationHeading: 'Odeeffannoo Quunnamtii',
    contactAdminSectionTitle: 'Bulchiinsa Mana Barumsaa fi Galmee',
    contactSchoolAdmin: 'Bulchiinsa mana barumsaa quunnamaa',
    phoneLabel: 'Bilbila',
    ourTeachersHeading: 'Barsiisota Keenya',
    noTeacherInfo: 'Odeeffannoon barsiisaa hin jiru',
    teacherManagementTitle: 'Bulchiinsa Barsiisotaa',
    addTeacherButton: 'Barsiisaa Dabalaa',
    editTeacherTitle: 'Barsiisaa Gulaalaa',
    teacherNamePlaceholder: 'Maqaa Barsiisaa',
    teacherPhonePlaceholder: 'Lakkoofsa Bilbilaa',
    teacherSubjectPlaceholder: 'Gosa Barnootaa',
    teacherTelegramPlaceholder: 'Maqaa Telegram (filannoo)',
    newsManagementTitle: 'Bulchiinsa Oduu',
    addNewsButton: 'Oduu Dabalaa',
    editNewsTitle: 'Oduu Gulaalaa',
    publishNotifyButton: 'Maxxansaa fi Beeksisuu',
    noNewsMessage: 'Oduun hin dabalamne',
    contactInformationManagementTitle: 'Bulchiinsa Odeeffannoo Quunnamtii',
    addPhoneNumberButton: 'Lakkoofsa Bilbilaa Dabalaa',
    schoolPhoneNumbersLabel: 'Lakkoofsa Bilbilaa Mana Barumsaa',
    contactTextLabel: 'Barreeffama Quunnamtii (bilbila waliin kan mul\'atu)',
    contactTextPlaceholder: 'fkn, Bulchiinsa Mana Barumsaa fi Galmee Quunnamaa',
    saveContactInformationButton: 'Odeeffannoo Quunnamtii Galchaa',
    savingLabel: 'Galchaa jira...',
    currentSettingsLabel: 'Qindoomina Ammaa:',
    portalUnderMaintenance: 'Portaalii Suphaa Irra Jira',
    portalClosedMessage: 'Portaaliin barataa yeroo ammaa haaromsaaf ykn suphaaf cufameera.',
    portalContactMessage: 'Maaloo bulchiinsa mana barumsaa quunnamaa ykn booda deebi\'aa yaalaa.',
    noResultsFound: 'Bu\'aan hin argamne.',
    yourGrades: 'Qabxii Keessan',
    cinematography: 'Siinimaatoograafii',
    videoEditing: 'Gulaallii Viidiyoo fi Sagalee',
    teacherNotSubmitted: 'Barsiisaan keessan qabxii keessan hin galchine.',
    pleaseContactThem: 'Maaloo isaan quunnamaa.',
    noGradesAvailable: 'Qabxiin ammatti hin jiru.',
    editMessage: 'Ergaa Gulaalaa',
    deleteMessage: 'Ergaa Haqa',
    saveChanges: 'Jijjiirama Galchaa',
    dismiss: 'Haqi',
    export: 'Ergi (Export)',
    exportGradeReport: 'Gabaasa Qabxii Ergi',
    studentIdLabel: 'Eenyummaa Barataa',
    newMessageTitle: 'Ergaa Haaraa',
    newMessageDescription: 'Barsiisaa keessan irraa ergaa haaraa argattaniittu.',
    viewAndReply: 'Ilaalaa fi Deebisaa',
    studentLabel: 'Barataa',
    replyPlaceholder: 'Barataaf deebii kennaa...',
    replySent: 'Deebiin ergameera!',
    replyFailed: 'Deebii erguun hin danda\'amne',
    superAdminAccess: 'Seensa Bulchiinsa Olaanaa',
    manageMasterPassword: 'Jechadaraa seensa olaanaa bulchaa',
    changePassword: 'Jechadaraa Jijjiiraa',
    newsAdminAccess: 'Seensa Bulchiinsa Oduu',
    manageNewsAdminAccess: 'Seensa bulchitoota oduu bulchaa',
    studentAdminAccess: 'Seensa Bulchiinsa Barataa',
    manageStudentAdminAccess: 'Seensa bulchitoota barataa bulchaa',
    sliderManagement: 'Bulchiinsa Islaayiderii',
    addImage: 'Suuraa Dabalaa',
    studentPortalAccess: 'Seensa Portaalii Barataa',
    portalActiveMessage: 'Barattoonni bu\'aa isaanii ilaaluu danda\'u',
    portalClosedMessageAdmin: 'Portaaliin cufameera. Barattoonni ergaa suphaa argu.',
    active: 'Hojjetaa Jira',
    closed: 'Cufameera',
    portalEnabledToast: 'Portaaliin barataa banameera',
    portalDisabledToast: 'Portaaliin barataa cufameera',
    cropImage: 'Suuraa Muruu',
    applyCrop: 'Muruu Hojii Irra Oolchaa',
    videoManagement: 'Bulchiinsa Viidiyoo',
    addVideo: 'Viidiyoo Dabalaa',
    noVideosInCategory: 'Ramaddii kana keessa viidiyoon hin jiru',
    editVideo: 'Viidiyoo Gulaalaa',
    addNewVideo: 'Viidiyoo Haaraa Dabalaa',
    titleLabel: 'Mataduree',
    videoTitlePlaceholder: 'Mataduree Viidiyoo',
    videoUrlLabel: 'URL Viidiyoo',
    categoryLabel: 'Ramaddii',
    subCategoryLabel: 'Ramaddii Xiqqaa',
    selectSubCategory: 'Ramaddii Xiqqaa Filadhaa',
    orderIndexLabel: 'Lakkoofsa Tartiibaa',
    visibleToStudentsLabel: 'Barattootaaf haa mul\'atu',
    save: 'Galchaa',
    preview: 'Dur-argii',
    edit: 'Gulaalaa',
    delete: 'Haqa',
    newsTitlePlaceholder: 'Mataduree Oduu',
    newsContentPlaceholder: 'Qabiyyee Oduu',
    newsImageLabel: 'Suuraa Oduu (Filannoo)',
    cropSelection: 'Filannoo Muruu',
    processing: 'Adeemsisaa jira...',
  },
  ar: {
    studentPanelButton: 'لوحة الطالب',
    adminPanelButton: 'لوحة المسؤول',
    studentPanelHeroTitle: 'مركز بلال الحبشي للتدريب على التصوير الفوتوغرافي والفيديو',
    studentPanelHeroSubtitle: 'بوابة الطالب - عرض أحدث النتائج',
    studentSearchTitle: 'ابحث عن نتيجتك',
    enterStudentIdPlaceholder: 'أدخل رقم الطالب',
    adminPanelHeroTitle: 'لوحة المسؤول',
    languageButton: 'اللغة',
    englishLabel: 'الإنجليزية',
    amharicLabel: 'الأمهرية',
    oromoLabel: 'أورومو',
    arabicLabel: 'العربية',
    schoolNewsHeading: 'أخبار المدرسة والإعلانات',
    schoolNewsTitle: 'أخبار المدرسة',
    noAnnouncements: 'لا توجد إعلانات في الوقت الحالي',
    clearAll: 'مسح الكل',
    noNewNotifications: 'لا توجد إشعارات جديدة',
    notifications: 'إشعارات',
    noNotifications: 'لا توجد إشعارات',
    addGradesTitle: 'إضافة درجات',
    editAllGradesTitle: 'تعديل جميع الدرجات',
    uploadPhoto: 'رفع صورة',
    studentIdPlaceholder: 'رقم الطالب (مثال: S1001)',
    studentNamePlaceholder: 'اسم الطالب',
    batchNumberPlaceholder: 'مثال: الدفعة 10',
    subjectNameLabel: 'اسم المادة',
    genderLabel: 'الجنس',
    genderPlaceholder: 'اختر الجنس',
    genderMale: 'ذكر',
    genderFemale: 'أنثى',
    genderAllOption: 'كل الأجناس',
    subjectsAndGrades: 'المواد والدرجات',
    cancel: 'إلغاء',
    addLabel: 'إضافة',
    addSubject: 'إضافة مادة',
    updateLabel: 'تحديث',
    gradeLabel: 'الدرجة',
    outOfLabel: 'من',
    saveGrades: 'حفظ الدرجات',
    updateGrades: 'تحديث',
    gradeLetterColumn: 'حرف الدرجة',
    gradeLetterOnAll: 'تشغيل الكل',
    gradeLetterOffAll: 'إيقاف الكل',
    viewColumn: 'عرض وإعادة تحرير',
    lockColumn: 'قفل',
    deleteColumn: 'حذف',
    recentComments: 'تعليقات الطلاب الأخيرة',
    recentTeacherComments: 'تعليقات المعلمين الأخيرة',
    noRecentComments: 'لا توجد تعليقات حديثة',
    noNewComments: 'ليس لديك تعليق جديد',
    reply: 'رد',
    chatWithTeacher: 'الدردشة مع المعلم',
    noMessagesYet: 'لا توجد رسائل بعد',
    teacherLabel: 'المعلم',
    youLabel: 'أنت',
    messagePlaceholder: 'اطرح سؤالاً أو أبلغ عن تصحيح...',
    searchPlaceholder: 'البحث بالاسم أو الرقم...',
    filterGradesLabel: 'تصفية حسب الدرجات',
    filterBatchLabel: 'تصفية حسب دفعة الطالب',
    filterGenderLabel: 'تصفية حسب الجنس',
    allStudents: 'كل الطلاب',
    photoColumn: 'صورة',
    idColumn: 'الرقم',
    nameColumn: 'الاسم',
    batchColumn: 'الدفعة',
    subjectsColumn: 'المواد',
    avgGradeColumn: 'متوسط الدرجة',
    actionsColumn: 'إجراءات',
    viewButton: 'عرض',
    gradeLetterOnLabel: 'تشغيل حرف الدرجة',
    gradeLetterOffLabel: 'إيقاف حرف الدرجة',
    signOut: 'تسجيل الخروج',
    poweredBy: 'مشغل بواسطة',
    languageMenuTitle: 'تغيير اللغة',
    languageHint: 'اختر اللغة التي يتحدث بها التطبيق',
    noGrades: 'لا توجد درجات',
    newLabel: 'جديد',
    studentGradeReportTitle: 'تقرير درجات الطالب',
    showAllResults: 'عرض كل النتائج',
    hideAllResults: 'إخفاء النتائج',
    totalSubjectsLabel: 'إجمالي المواد',
    totalGradeLabel: 'إجمالي الدرجة',
    allSubjectsAndGradesTitle: 'كل المواد والدرجات',
    studentToggleLabel: 'للوحة الطلاب فقط',
    managementToggleLabel: 'لوحة الإدارة',
    adminAccessTitle: 'وصول المسؤول',
    adminAccessSubtitle: 'أدخل كلمة المرور للمتابعة',
    signIn: 'تسجيل الدخول',
    passwordPlaceholder: 'كلمة المرور',
    appLockedTitle: 'التطبيق مقفل',
    appLockedMessage: 'محاولات خاطئة كثيرة جدا. يرجى الانتظار.',
    appLockedFooter: 'سيعود التطبيق إلى شاشة الترحيب تلقائيًا',
    genderRequiredMessage: 'يرجى اختيار الجنس',
    contactInformationHeading: 'معلومات الاتصال',
    contactAdminSectionTitle: 'إدارة المدرسة والتسجيل',
    contactSchoolAdmin: 'اتصل بمسؤول المدرسة',
    phoneLabel: 'هاتف',
    ourTeachersHeading: 'معلمونا',
    noTeacherInfo: 'لا تتوفر معلومات المعلم',
    teacherManagementTitle: 'إدارة المعلمين',
    addTeacherButton: 'إضافة معلم',
    editTeacherTitle: 'تعديل المعلم',
    teacherNamePlaceholder: 'اسم المعلم',
    teacherPhonePlaceholder: 'رقم الهاتف',
    teacherSubjectPlaceholder: 'المادة',
    teacherTelegramPlaceholder: 'اسم مستخدم تيليجرام (اختياري)',
    newsManagementTitle: 'إدارة الأخبار',
    addNewsButton: 'إضافة خبر',
    editNewsTitle: 'تعديل الخبر',
    publishNotifyButton: 'نشر وإشعار',
    noNewsMessage: 'لم تتم إضافة أخبار بعد',
    contactInformationManagementTitle: 'إدارة معلومات الاتصال',
    addPhoneNumberButton: 'إضافة رقم هاتف',
    schoolPhoneNumbersLabel: 'أرقام هواتف المدرسة',
    contactTextLabel: 'نص الاتصال (يظهر مع أرقام الهواتف)',
    contactTextPlaceholder: 'مثال: اتصل بمسؤول المدرسة والتسجيل',
    saveContactInformationButton: 'حفظ معلومات الاتصال',
    savingLabel: 'جاري الحفظ...',
    currentSettingsLabel: 'الإعدادات الحالية:',
    portalUnderMaintenance: 'البوابة تحت الصيانة',
    portalClosedMessage: 'بوابة الطالب مغلقة حاليًا للتحديثات أو الصيانة.',
    portalContactMessage: 'يرجى الاتصال بإدارة المدرسة أو التحقق لاحقًا.',
    noResultsFound: 'لم يتم العثور على نتائج.',
    yourGrades: 'درجاتك',
    cinematography: 'التصوير السينمائي',
    videoEditing: 'تحرير الفيديو والصوت',
    teacherNotSubmitted: 'لم يقم معلمك بتقديم درجاتك بعد.',
    pleaseContactThem: 'يرجى الاتصال بهم.',
    noGradesAvailable: 'لا توجد درجات متاحة بعد.',
    editMessage: 'تعديل الرسالة',
    deleteMessage: 'حذف الرسالة',
    saveChanges: 'حفظ التغييرات',
    dismiss: 'تجاهل',
    export: 'تصدير',
    exportGradeReport: 'تصدير تقرير الدرجات',
    studentIdLabel: 'رقم الطالب',
    newMessageTitle: 'رسالة جديدة',
    newMessageDescription: 'لقد تلقيت رسالة جديدة من معلمك.',
    viewAndReply: 'عرض ورد',
    studentLabel: 'طالب',
    replyPlaceholder: 'الرد على الطالب...',
    replySent: 'تم إرسال الرد!',
    replyFailed: 'فشل إرسال الرد',
    superAdminAccess: 'وصول المشرف العام',
    sliderManagement: 'إدارة شرائح العرض',
    videoManagement: 'إدارة الفيديو',
    newsManagement: 'إدارة الأخبار',
    teacherManagement: 'إدارة المعلمين',
    portalManagement: 'إدارة البوابة',
    contactManagement: 'إدارة جهات الاتصال',
    adminDashboard: 'لوحة تحكم المشرف',
    welcomeAdmin: 'مرحبًا، المشرف',
    selectModuleToManage: 'اختر وحدة للإدارة',
    backToDashboard: 'العودة إلى لوحة التحكم',
    addSlide: 'إضافة شريحة',
    editSlide: 'تعديل الشريحة',
    deleteSlide: 'حذف الشريحة',
    slideTitle: 'عنوان الشريحة',
    slideDescription: 'وصف الشريحة',
    slideImage: 'صورة الشريحة',
    saveSlide: 'حفظ الشريحة',
    addVideo: 'إضافة فيديو',
    editVideo: 'تعديل الفيديو',
    deleteVideo: 'حذف الفيديو',
    videoTitle: 'عنوان الفيديو',
    videoUrl: 'رابط الفيديو',
    videoThumbnail: 'صورة مصغرة للفيديو',
    saveVideo: 'حفظ الفيديو',
    addTeacher: 'إضافة معلم',
    editTeacher: 'تعديل المعلم',
    deleteTeacher: 'حذف المعلم',
    teacherName: 'اسم المعلم',
    teacherSubject: 'مادة المعلم',
    teacherPhone: 'هاتف المعلم',
    teacherEmail: 'بريد المعلم الإلكتروني',
    saveTeacher: 'حفظ المعلم',
    portalSettings: 'إعدادات البوابة',
    maintenanceMode: 'وضع الصيانة',
    enableMaintenanceMode: 'تفعيل وضع الصيانة',
    maintenanceMessage: 'رسالة الصيانة',
    saveSettings: 'حفظ الإعدادات',
    contactInfo: 'معلومات الاتصال',
    address: 'العنوان',
    phone: 'الهاتف',
    email: 'البريد الإلكتروني',
    saveContact: 'حفظ جهة الاتصال',
    manageMasterPassword: 'إدارة كلمة مرور الوصول الرئيسية',
    changePassword: 'تغيير كلمة المرور',
    newsAdminAccess: 'وصول مشرف الأخبار',
    manageNewsAdminAccess: 'إدارة الوصول لمشرفي الأخبار',
    studentAdminAccess: 'وصول مشرف الطلاب',
    manageStudentAdminAccess: 'إدارة الوصول لمشرفي الطلاب',
    addImage: 'إضافة صورة',
    cropImage: 'قص الصورة',
    applyCrop: 'تطبيق القص',
    save: 'حفظ',
    processing: 'جاري المعالجة...',
    cropSelection: 'قص التحديد',
    addNewVideo: 'إضافة فيديو جديد',
    titleLabel: 'العنوان',
    videoTitlePlaceholder: 'عنوان الفيديو',
    videoUrlLabel: 'رابط الفيديو',
    categoryLabel: 'الفئة',
    subCategoryLabel: 'الفئة الفرعية',
    selectSubCategory: 'اختر الفئة الفرعية',
    orderIndexLabel: 'ترتيب العرض',
    visibleToStudentsLabel: 'مرئي للطلاب',
    preview: 'معاينة',
    edit: 'تعديل',
    delete: 'حذف',
    noVideosInCategory: 'لا توجد مقاطع فيديو في هذه الفئة',
    newsTitlePlaceholder: 'عنوان الخبر',
    newsContentPlaceholder: 'محتوى الخبر',
    newsImageLabel: 'صورة الخبر (اختياري)',
    studentPortalAccess: 'وصول بوابة الطالب',
    portalActiveMessage: 'يمكن للطلاب عرض نتائجهم',
    portalClosedMessageAdmin: 'البوابة مغلقة. يرى الطلاب رسالة صيانة.',
    active: 'نشط',
    closed: 'مغلق',
    portalEnabledToast: 'تم تفعيل بوابة الطالب',
    portalDisabledToast: 'تم تعطيل بوابة الطالب',
  },
} as const;

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<AppLanguage>(() => {
    if (typeof window === 'undefined') return 'en';
    const stored = window.localStorage.getItem('appLanguage');
    return (stored === 'am' || stored === 'or' || stored === 'ar') ? stored : 'en';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('appLanguage', language);
      document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.lang = language;
    }
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (key: TranslationKey) => translations[language][key] ?? translations.en[key],
    dir: language === 'ar' ? 'rtl' : 'ltr',
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
