import { createContext, useContext, useEffect, useMemo, useState, ReactNode } from 'react';

export type AppLanguage = 'en' | 'am';

type TranslationKey = keyof typeof translations.en;

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (lang: AppLanguage) => void;
  t: (key: TranslationKey) => string;
};

const translations = {
  en: {
    studentPanelButton: 'Student Panel',
    adminPanelButton: 'Admin Panel',
    studentPanelHeroTitle: 'BILALUL HABESHI TRAINING CENTER',
    studentPanelHeroSubtitle: 'Student Portal - View your latest result',
    studentSearchTitle: 'Search Your Result',
    enterStudentIdPlaceholder: 'Enter your Student ID',
    adminPanelHeroTitle: 'Admin Panel',
    languageButton: 'Language',
    englishLabel: 'English',
    amharicLabel: 'Amharic',
    schoolNewsHeading: 'School News & Announcements',
    schoolNewsTitle: 'School News',
    noAnnouncements: 'No announcements at this time',
    clearAll: 'Clear All',
    noNewNotifications: 'No new notifications',
    addGradesTitle: 'Add Grades',
    editAllGradesTitle: 'Edit All Grades',
    uploadPhoto: 'Upload Photo',
    studentIdPlaceholder: 'Student ID (e.g., S1001)',
    studentNamePlaceholder: 'Student Name',
    batchNumberPlaceholder: 'e.g., Batch 10',
    subjectNameLabel: 'Subject Name',
    genderLabel: 'Gender',
    genderPlaceholder: 'Select gender',
    genderMale: 'Male',
    genderFemale: 'Female',
    genderAllOption: 'All Gender',
    subjectsAndGrades: 'Subjects & Grades',
    cancel: 'Cancel',
    addLabel: 'Add',
    addSubject: 'Add Subject',
    updateLabel: 'Update',
    gradeLabel: 'Grade',
    outOfLabel: 'Out of',
    saveGrades: 'Save Grades',
    updateGrades: 'UPDATE',
    gradeLetterColumn: 'GRADE LETTER',
    viewColumn: 'VIEW & RE-EDIT',
    lockColumn: 'LOCK',
    deleteColumn: 'DELETE',
    exportGradeReport: 'Export Grade Report',
    recentComments: 'Recent Student Comments',
    recentTeacherComments: 'Recent Teacher Comments',
    noRecentComments: 'No recent comments',
    noNewComments: "You don't have a new comment",
    reply: 'Reply',
    chatWithTeacher: 'Chat with Teacher',
    noMessagesYet: 'No messages yet',
    teacherLabel: 'Teacher',
    youLabel: 'You',
    messagePlaceholder: 'Ask a question or report a correction...',
    searchPlaceholder: 'Search by name or ID...',
    filterGradesLabel: 'FILTER BY GRADES',
    filterBatchLabel: 'FILTER BY STUDENT BATCH',
    filterGenderLabel: 'FILTER BY GENDER',
    allStudents: 'All Students',
    photoColumn: 'Photo',
    idColumn: 'ID',
    nameColumn: 'Name',
    batchColumn: 'Batch',
    subjectsColumn: 'Subj',
    avgGradeColumn: 'Avg Grade',
    actionsColumn: 'Actions',
    viewButton: 'View',
    gradeLetterOnLabel: 'Grade Letter ON',
    gradeLetterOffLabel: 'Grade Letter OFF',
    signOut: 'Sign Out',
    poweredBy: 'Powered By',
    languageMenuTitle: 'Change Language',
    languageHint: 'Choose how the app speaks to you',
    noGrades: 'No grades',
    newLabel: 'New',
    studentGradeReportTitle: 'Student Grade Report',
    showAllResults: 'See all results',
    hideAllResults: 'Hide results',
    totalSubjectsLabel: 'Total Subjects',
    totalGradeLabel: 'Total Grade',
    allSubjectsAndGradesTitle: 'All Subjects & Grades',
    studentToggleLabel: 'For Students Panel Only',
    managementToggleLabel: 'Management Panel',
    adminAccessTitle: 'Admin Access',
    adminAccessSubtitle: 'Enter password to continue',
    signIn: 'Sign In',
    passwordPlaceholder: 'Password',
    appLockedTitle: 'App Locked',
    appLockedMessage: 'Too many incorrect attempts. Please wait.',
    appLockedFooter: 'App will return to welcome screen automatically',
    genderRequiredMessage: 'Please select a gender',
    contactInformationHeading: 'Contact Information',
    contactAdminSectionTitle: 'School Administration & Registration',
    contactSchoolAdmin: 'Contact the school admin',
    phoneLabel: 'Phone',
    ourTeachersHeading: 'Our Teachers',
    noTeacherInfo: 'No teacher information available',
    teacherManagementTitle: 'Teacher Management',
    addTeacherButton: 'Add Teacher',
    editTeacherTitle: 'Edit Teacher',
    teacherNamePlaceholder: 'Teacher Name',
    teacherPhonePlaceholder: 'Phone Number',
    teacherSubjectPlaceholder: 'Subject',
    teacherTelegramPlaceholder: 'Telegram Username (optional)',
    newsManagementTitle: 'News Management',
    addNewsButton: 'Add News',
    editNewsTitle: 'Edit News',
    publishNotifyButton: 'Publish & Notify',
    noNewsMessage: 'No news added yet',
    contactInformationManagementTitle: 'Contact Information Management',
    addPhoneNumberButton: 'Add Phone Number',
    schoolPhoneNumbersLabel: 'School Phone Numbers',
    contactTextLabel: 'Contact Text (displayed with phone numbers)',
    contactTextPlaceholder: 'e.g., Contact School Admin & Registration',
    saveContactInformationButton: 'Save Contact Information',
    savingLabel: 'Saving...',
    currentSettingsLabel: 'Current Settings:',
  },
  am: {
    studentPanelButton: 'የተማሪ ፓነል',
    adminPanelButton: 'የአስተዳዳሪ ፓነል',
    studentPanelHeroTitle: 'እንኳን ወደ ቢላልሉል ሀበሺ የስልጠና ማዕከል በደህና መጡ',
    studentPanelHeroSubtitle: 'የተማሪ ፖርታል - የቅርብ ውጤትዎን ይመልከቱ',
    studentSearchTitle: 'ውጤትዎን ፈልጉ',
    enterStudentIdPlaceholder: 'የተማሪ መለያዎን ያስገቡ',
    adminPanelHeroTitle: 'የአስተዳዳሪ ፓነል',
    languageButton: 'ቋንቋ',
    englishLabel: 'እንግሊዝኛ',
    amharicLabel: 'አማርኛ',
    schoolNewsHeading: 'የትምህርት ቤት ዜናና መግለጫዎች',
    schoolNewsTitle: 'የትምህርት ቤት ዜና',
    noAnnouncements: 'በአሁኑ ጊዜ ማስታወቂያ የለም',
    clearAll: 'ሁሉንም አጥፋ',
    noNewNotifications: 'አዲስ ማሳወቂያ የለም',
    addGradesTitle: 'ውጤት ጨምር',
    editAllGradesTitle: 'ሁሉንም ውጤት አርትዕ',
    uploadPhoto: 'ፎቶ አስገባ',
    studentIdPlaceholder: 'የተማሪ መለያ (ለምሳሌ፣ S1001)',
    studentNamePlaceholder: 'የተማሪ ስም',
    batchNumberPlaceholder: 'ለምሳሌ፣ ባች 10',
    subjectNameLabel: 'የትምህርት ስም',
    genderLabel: 'ጾታ',
    genderPlaceholder: 'ጾታ ይምረጡ',
    genderMale: 'ወንድ',
    genderFemale: 'ሴት',
    genderAllOption: 'ሁሉም ጾታ',
    subjectsAndGrades: 'ትምህርቶች እና ውጤቶች',
    cancel: 'ሰርዝ',
    addLabel: 'ጨምር',
    addSubject: 'ትምህርት ጨምር',
    updateLabel: 'አዘምን',
    gradeLabel: 'ውጤት',
    outOfLabel: 'ከ',
    saveGrades: 'ውጤት አስቀምጥ',
    updateGrades: 'አዘምን',
    exportGradeReport: 'የውጤት ሪፖርት ውጣ',
    recentComments: 'የተማሪዎች አስተያየቶች',
    recentTeacherComments: 'የመምህራን አስተያየቶች',
    noRecentComments: 'የቅርብ አስተያየት የለም',
    noNewComments: 'አዲስ አስተያየት የለም',
    reply: 'መልስ',
    chatWithTeacher: 'ከመምህር ጋር ይወያዩ',
    noMessagesYet: 'ገና መልዕክት የለም',
    teacherLabel: 'መምህር',
    youLabel: 'እርስዎ',
    messagePlaceholder: 'ጥያቄ ይጠይቁ ወይም ስህተት ያሳውቁ...',
    searchPlaceholder: 'በስም ወይም በመለያ ፈልግ...',
    filterGradesLabel: 'የውጤት ማጣሪያ',
    filterBatchLabel: 'የባች ማጣሪያ',
    filterGenderLabel: 'ጾታ ይማጣሩ',
    allStudents: 'ሁሉም ተማሪዎች',
    photoColumn: 'ፎቶ',
    idColumn: 'መለያ',
    nameColumn: 'ስም',
    batchColumn: 'ባች',
    subjectsColumn: 'ትምህርቶች',
    avgGradeColumn: 'አማካይ ውጤት',
    actionsColumn: 'እርምጃዎች',
    viewButton: 'እይታ',
    gradeLetterOnLabel: 'የግሬድ ፊደል ክፈት',
    gradeLetterOffLabel: 'የግሬድ ፊደል ዝጋ',
    signOut: 'ውጣ',
    poweredBy: 'በ',
    languageMenuTitle: 'ቋንቋ ለውጥ',
    languageHint: 'መተግበሪያው የሚናገረውን ቋንቋ ይምረጡ',
    noGrades: 'ውጤት የለም',
    newLabel: 'አዲስ',
    studentGradeReportTitle: 'የተማሪ ውጤት ሪፖርት',
    showAllResults: 'ሁሉንም ውጤቶች አሳይ',
    hideAllResults: 'ሁሉንም ውጤቶች ደብቅ',
    totalSubjectsLabel: 'ጠቅላላ ትምህርቶች',
    totalGradeLabel: 'ጠቅላላ ውጤት',
    allSubjectsAndGradesTitle: 'ሁሉም ትምህርቶች እና ውጤቶች',
    studentToggleLabel: 'ለተማሪዎች ፓነል ብቻ',
    managementToggleLabel: 'የአስተዳዳሪ መቆጣጠሪያ',
    adminAccessTitle: 'የአስተዳዳሪ መዳረሻ',
    adminAccessSubtitle: 'ለመቀጠል የይለፍ ቃል ያስገቡ',
    signIn: 'ግባ',
    passwordPlaceholder: 'የይለፍ ቃል',
    appLockedTitle: 'መተግበሪያው ተቆልፏል',
    appLockedMessage: 'ብዙ ጊዜ በስህተት አስገቡ። እባክዎ ይጠብቁ።',
    appLockedFooter: 'መተግበሪያው ወደ መነሻ ገጽ በራሱ ይመለሳል',
    genderRequiredMessage: 'እባክዎ ጾታ ይምረጡ',
    contactInformationHeading: 'የእውቂያ መረጃ',
    contactAdminSectionTitle: 'የትምህርት ቤት አስተዳዳሪና መመዝገቢያ',
    contactSchoolAdmin: 'የትምህርት ቤቱን አስተዳዳሪ ያነጋግሩ',
    phoneLabel: 'ስልክ',
    ourTeachersHeading: 'መምህራን ቡድናችን',
    noTeacherInfo: 'የመምህራን መረጃ አልተጨመረም',
    teacherManagementTitle: 'የመምህራን አስተዳደር',
    addTeacherButton: 'መምህር ጨምር',
    editTeacherTitle: 'መምህር አርትዕ',
    teacherNamePlaceholder: 'የመምህር ስም',
    teacherPhonePlaceholder: 'ስልክ ቁጥር',
    teacherSubjectPlaceholder: 'ትምህርት',
    teacherTelegramPlaceholder: 'የቴሌግራም ዩዘርኔም (አማራጭ)',
    newsManagementTitle: 'የዜና አስተዳደር',
    addNewsButton: 'ዜና ጨምር',
    editNewsTitle: 'ዜና አርትዕ',
    publishNotifyButton: 'አትም እና አሳውቅ',
    noNewsMessage: 'የታቀመ ዜና የለም',
    contactInformationManagementTitle: 'የእውቂያ መረጃ አስተዳደር',
    addPhoneNumberButton: 'የስልክ ቁጥር ጨምር',
    schoolPhoneNumbersLabel: 'የትምህርት ቤት ስልክ ቁጥሮች',
    contactTextLabel: 'በስልክ ቁጥሮች ጋር የሚታየው ጽሑፍ',
    contactTextPlaceholder: 'ለምሳሌ፣ የትምህርት ቤት አስተዳዳሪን እና መመዝገቢያን ያነጋግሩ',
    saveContactInformationButton: 'የእውቂያ መረጃ አስቀምጥ',
    savingLabel: 'በመቀመጥ ላይ...',
    currentSettingsLabel: 'የአሁኑ ቅንብሮች፡',
  },
} as const;

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<AppLanguage>(() => {
    if (typeof window === 'undefined') return 'en';
    const stored = window.localStorage.getItem('appLanguage');
    return stored === 'am' ? 'am' : 'en';
  });

  useEffect(() => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('appLanguage', language);
    }
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage,
    t: (key: TranslationKey) => translations[language][key] ?? translations.en[key],
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
