// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Safely create a Supabase client. In mobile (Capacitor) builds the Vite env
// vars may be missing which can cause runtime errors. If creation fails,
// export a lightweight stub that returns empty results to avoid crashing the app.
function createStubClient() {
  const terminalResult = async () => ({ data: null, error: null });
  // Build a chainable query builder that returns itself for query methods
  const chainable = () => {
    const q: any = {
      select: (_cols?: string) => q,
      order: (_col?: string) => q,
      eq: (_field?: string, _value?: any) => q,
      // terminal methods return a promise mimicking Supabase response
      maybeSingle: terminalResult,
      single: terminalResult,
      insert: terminalResult,
      update: terminalResult,
      delete: terminalResult,
      then: (cb: any) => Promise.resolve(terminalResult()).then(cb),
    };
    return q;
  };
  return {
    auth: {
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      getSession: async () => ({ data: { session: null } }),
      signInWithPassword: async () => ({ error: { message: 'Supabase not configured' } }),
      signUp: async () => ({ error: { message: 'Supabase not configured' } }),
      signOut: async () => ({ error: null }),
    },
    from: () => chainable(),
    channel: () => ({ on: () => ({ subscribe: async () => ({}) }), subscribe: async () => ({}) }),
    removeChannel: () => {},
  } as any;
}

let supabase: any;
try {
  // createClient tolerates empty strings, but wrap in try/catch just in case
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
} catch (err) {
  console.warn('Supabase client creation failed, using stub client:', err);
  supabase = createStubClient();
}

export { supabase };